Repository kyma-project/helm-broker, pull requests merged in 2019-10, with the labels that each got.

#40 Fix etcd client timeout
  Gopkg.lock
  charts/helm-broker/templates/deploy.yaml
  charts/helm-broker/templates/helm-broker-cfg.yaml
  charts/helm-broker/values.yaml
  cmd/broker/main.go
  cmd/controller/main.go
  internal/broker/server.go
  internal/config/config.go
  internal/config/controller_config.go
  internal/health/broker.go
  internal/health/controller.go
  internal/health/health.go
  internal/storage/driver/etcd/client.go
  internal/storage/driver/etcd/driver.go
  internal/storage/factory_test.go
  internal/storage/storage.go
  internal/storage/testdata/Config.golden.go
Labels: area/service-catalog

#43 Upgrade readme file
  README.md
  hack/run-dev-kind.sh
  pkg/README.md
  test/README.md
Labels: area/documentation, area/service-catalog

#45 Create release process
  .github_changelog_generator
  .gitignore
  Makefile
  README.md
  charts/helm-broker/templates/deploy.yaml
  charts/helm-broker/templates/tests/test-addons-serving.yaml
  charts/helm-broker/values.yaml
  docs/releasing.md
  hack/README.md
  hack/ci/lib/utilities.sh
  hack/ci/run-chart-test.sh
  hack/release/create_latest_tag.sh
  hack/release/create_release_branch.sh
  hack/release/generate_changelog.sh
  hack/release/get_yq.sh
  hack/release/push_release.sh
  hack/release/remove_latest_tag.sh
Labels: area/documentation, enhancement
