Repository kyma-project/helm-broker, pull requests merged in 2019-09, with the labels that each got.

#28 S3 integration test
  Gopkg.lock
  README.md
  internal/addon/provider/gcs.go
  internal/controller/setup.go
  test/integration/deps_install_test.go
  test/integration/fake_s3_repository_test.go
  test/integration/integration_test.go
  test/integration/suite_test.go
  test/integration/testdata/addons-s3.tgz
Labels: area/service-catalog, enhancement

#37 Apply minor changes to utilities.sh script
  charts/helm-broker/values.yaml
  hack/ci/lib/deps_ver.sh
  hack/ci/lib/utilities.sh
  hack/ci/run-chart-test.sh
  test/charts/helm_broker_test.go
Labels: bug, enhancement

#36 Add controller liveness probe with controller flow
  charts/helm-broker/templates/deploy.yaml
  charts/helm-broker/templates/rbac.yaml
  cmd/controller/main.go
  internal/broker/server.go
  internal/health/health.go
Labels: area/service-catalog

#39 Add Maja and Alex to CODEOWNERS
  CODEOWNERS
Labels: area/documentation
