Repository kyma-project/helm-broker, pull requests merged in 2020-01, with the labels that each got.

#78 Put metrics endpoint to separate server with own port
  charts/helm-broker/templates/deploy.yaml
  charts/helm-broker/values.yaml
  cmd/broker/main.go
  internal/broker/server.go
  internal/config/config.go
Labels: area/service-catalog

#81 changing the way to generate a name for a release
  Gopkg.lock
  Gopkg.toml
  internal/broker/fixture_test.go
  internal/broker/provision.go
  internal/broker/provision_export_test.go
  internal/controller/common.go
Labels: area/service-catalog

#82 Run chart testing always with image from pr
  Makefile
  before-commit.sh
  charts/helm-broker/ci/README.md
  charts/helm-broker/ci/built-image-values.yaml
  charts/helm-broker/templates/deploy.yaml
  charts/helm-broker/templates/tests/test-addons-serving.yaml
  charts/helm-broker/values.yaml
  hack/build-binaries.sh
  hack/ci/lib/utilities.sh
  hack/ci/run-chart-test.sh
Labels: area/ci, area/service-catalog, enhancement

#83 Fix chart diff between kyma and this repo
  charts/helm-broker/templates/crd/addons-configuration.crd.yaml
  charts/helm-broker/templates/crd/cluster-addons-configuration.crd.yaml
  charts/helm-broker/templates/default-addons-cfg.yaml
  charts/helm-broker/templates/deploy.yaml
  charts/helm-broker/templates/helm-broker-cfg.yaml
  charts/helm-broker/templates/helm-secret.yaml
  charts/helm-broker/templates/rbac.yaml
  charts/helm-broker/templates/svc.yaml
  charts/helm-broker/values.yaml
  pkg/apis/addons/v1alpha1/types.go
Labels: area/service-catalog, enhancement

#85 Enable stale bot for epics
  .github/stale.yml
Labels: area/community
