Repository kyma-project/helm-broker, pull requests merged in 2021-08, with the labels that each got.

#166 Github: update deprecated authorization
  deploy/controller/Dockerfile
  hack/release/push_release.sh
Labels: lgtm, size/XS

#169 Remove kazydek from CODEOWNERS
  CODEOWNERS
Labels: area/community, area/documentation, size/XS, lgtm

#168 Add azure-service-broker image swap webhook
  Makefile
  charts/helm-broker/ci/built-image-values.yaml
  charts/helm-broker/templates/default-addons-cfg.yaml
  charts/helm-broker/templates/webhook-deployment.yaml
  charts/helm-broker/templates/webhook-register.yaml
  charts/helm-broker/templates/webhook-service.yaml
  charts/helm-broker/values.yaml
  cmd/broker/main.go
  cmd/controller/main.go
  cmd/webhook/main.go
  deploy/webhook/Dockerfile
  go.mod
  go.sum
  hack/build-binaries.sh
  hack/ci/lib/deps_ver.sh
  hack/ci/lib/utilities.sh
  hack/ci/run-chart-test.sh
  internal/webhook/mutate.go
  internal/webhook/mutate_test.go
Labels: size/XL, lgtm

#172 Bump helm and moby modules versions
  go.mod
  go.sum
Labels: size/M, lgtm

#174 Edit apk add to target higher git versions
  deploy/controller/Dockerfile
Labels: size/XS, lgtm
