Repository kyma-project/helm-broker, pull requests merged in 2021-11, with the labels that each got.

#186 Sanitize http resposne
  CODEOWNERS
  internal/broker/server.go
Labels: size/XS, lgtm

#187 Sanitize values provided by the user
  internal/broker/server.go
Labels: size/M, lgtm

#188 Fix security vulnerabilities
  charts/helm-broker/values.yaml
  deploy/controller/Dockerfile
  go.mod
  go.sum
Labels: size/S, lgtm
